spring:
  application:
    name: auth-service

  cloud:
    vault:
      uri: http://localhost:8200
      token: root # ou melhor, use um token seguro via env
      kv:
        enabled: true
        backend: secret
        default-context: pagamento/auth-service
jwt:
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}
