# ========================================================
# Arquivo: application.yml
# Serviço: card-service
# Projeto: pagamento-system21
# Descrição: Configurações Spring Boot, Cassandra, JWT e log.
# ========================================================

spring:
  application:
    name: card-service
  main:
    banner-mode: off
  jackson:
    serialization:
      indent-output: true

  data:
    cassandra:
      keyspace-name: pagamento_card
      contact-points: 127.0.0.1
      port: 9042
      schema-action: create-if-not-exists

  datasource:
    url: jdbc:postgresql://localhost:5432/pagamento
    username: user
    password: pass

server:
  port: 8084  # Ajuste conforme necessário

logging:
  level:
    root: INFO

jwt:
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}
