---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
      - org.springframework.cloud.vault.config.VaultAutoConfiguration

management:
  health:
    vault:
      enabled: false

logging:
  level:
    root: WARN
    com.pagamento.boleto: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
