# ============================
# Arquivo: application.yml
# Serviço: boleto-service
# Projeto: pagamento-system21
# ============================

spring:
  application:
    name: boleto-service
  main:
    banner-mode: off
  jackson:
    serialization:
      indent-output: true
  profiles:
    active: jpa  # Perfil padrão
  
  # Configurações do Kafka (comum a todos os perfis)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Configurações adicionais para produção segura
      acks: all
      retries: 3
      max-in-flight-requests-per-connection: 1
      enable-idempotence: true
      compression-type: snappy

server:
  port: 8082

logging:
  level:
    root: INFO
    com.pagamento.boleto: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET:secretKey}
  expiration: ${JWT_EXPIRATION:3600000}  # 1 hora em milissegundos

# Configuração específica para perfil JPA
---
spring:
  config:
    activate:
      on-profile: jpa
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:boleto}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  data:
    mongodb:
      enabled: false  # Desabilita MongoDB quando JPA está ativo

# Configuração específica para perfil MongoDB
---
spring:
  config:
    activate:
      on-profile: mongo
  data:
    mongodb:
      enabled: true
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:boleto}
      authentication-database: admin
      username: ${MONGO_USER:user}
      password: ${MONGO_PASSWORD:pass}
  jpa:
    enabled: false  # Desabilita JPA quando MongoDB está ativo

# Configuração específica para produção
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER}" password="${KAFKA_PASSWORD}";
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    hikari:
      connection-init-sql: "SET TIME ZONE 'UTC'"
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC