# Spring Boot Configuration
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pagamento
    username: user
    password: pass
jwt:
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}

