# =============================================================================
# Arquivo: application.yml
# Ambiente: Produção
# Projeto: api-gateway (módulo do pagamento-system21)
# Finalidade: Configuração de Gateway com Redis, Resiliência, CORS, RateLimiter,
#             Circuit Breaker, Retry e Observabilidade via Prometheus
# Observação: Os valores com ${...} podem ser sobrescritos por variáveis de ambiente
# =============================================================================

server:
  port: 8080  # Porta padrão do serviço gateway em produção

spring:
  application:
    name: api-gateway

  profiles:
    active: prod  #  Corrigido para produção (antes estava como "test")

  data:
    redis:
      host: ${REDIS_HOST:localhost}  # Pode ser definido via var. ambiente
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      enabled: true

      discovery:
        locator:
          enabled: false  # Desativa mapeamento automático de services

      httpclient:
        connect-timeout: 1000        # Tempo de conexão em milissegundos
        response-timeout: 5s         # Tempo máximo para resposta
        pool:
          max-idle-time: 60s         # Tempo máximo de ociosidade do pool

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE

      routes:
        - id: pix-service
          uri: lb://pix-service
          predicates:
            - Path=/pix/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: pixCircuitBreaker
                fallbackUri: forward:/fallback/pix
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                backoff:
                  firstBackoff: 500ms
                  maxBackoff: 5s
                  factor: 2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                backoff:
                  firstBackoff: 500ms
                  maxBackoff: 5s
                  factor: 2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: rate_limiter_route
          uri: lb://auth-service
          predicates:
            - Path=/auth/admin/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

  cors:
    allowed-origins: "https://pagamento.com.br, https://app.pagamento.com.br"
    allowed-methods: "GET,POST,OPTIONS"
    allowed-headers: "Authorization,Content-Type,X-Requested-With"
    exposed-headers: "X-Custom-Header,X-Rate-Limit"

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50           # % de falhas para abrir o circuito
        minimum-number-of-calls: 10          # Número mínimo de chamadas para avaliar
        sliding-window-type: TIME_BASED
        sliding-window-size: 10              # Janela de tempo para amostragem
        wait-duration-in-open-state: 10s     # Tempo que o circuito fica aberto
    instances:
      pixCircuitBreaker:
        baseConfig: default
      authCircuitBreaker:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeout-duration: 5s

eureka:
  client:
    enabled: false  # Desabilitado se descoberta for manual ou via DNS

cache:
  type: caffeine  # Cache local (usado apenas se ativar @Cacheable)

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: WARN
    reactor.netty: WARN
    com.pagamento.gateway: DEBUG  # Logs detalhados dos filtros do projeto

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, gateway
      cors:
        allowed-origins: "*"   # Permite integração com Prometheus, Grafana, etc.
        allowed-methods: "*"

  prometheus:
    metrics:
      export:
        enabled: true  # Novo formato para habilitar exportação de métricas

  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    health:
      show-details: always  # Exibe informações detalhadas no /actuator/health

