server:
  port: 0

spring:
  cloud:
    gateway:
      routes:
        - id: pix-service
          uri: http://localhost:${wiremock.server.port}
          predicates:
            - Path=/pix/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://localhost:${wiremock.server.port}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: test-route
          uri: http://localhost:${wiremock.server.port}
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

resilience4j:
  circuitbreaker:
    instances:
      pixCircuitBreaker:
        register-health-indicator: false
        failure-rate-threshold: 100
        minimum-number-of-calls: 1
      authCircuitBreaker:
        register-health-indicator: false
        failure-rate-threshold: 100
        minimum-number-of-calls: 1
  retry:
    instances:
      pix-service:
        max-attempts: 1
      auth-service:
        max-attempts: 1

# Configurações e