version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      
  auth-service:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      
  # Add other services similarly
