name: Boleto Service CI/CD

on:
  push:
    paths:
      - 'boleto-service/**'
  pull_request:
    paths:
      - 'boleto-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build e testes com Maven
        run: |
          cd boleto-service
          mvn clean install

      - name: Upload de artefato JAR
        uses: actions/upload-artifact@v4
        with:
          name: boleto-service-jar
          path: boleto-service/target/*.jar
