name: Build & Test All Microservices

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build all modules via parent POM
        run: mvn clean install -f pom.xml

  unit-tests:
    runs-on: ubuntu-latest
    needs: build-all

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests with coverage
        run: mvn test jacoco:report

  integration-tests:
    runs-on: ubuntu-latest
    needs: build-all
    services:
      cassandra:
        image: cassandra:4.0
        ports:
          - 9042:9042
      kafka:
        image: confluentinc/cp-kafka:7.0.0
        ports:
          - 9092:9092
        env:
          KAFKA_LISTENERS: PLAINTEXT://:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run integration tests
        run: mvn verify -DskipUnitTests=true failsafe:integration-test
        env:
          SPRING_CASSANDRA_CONTACT_POINTS: localhost
          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
